### ISSUE TITLE
链表 Linked List【数据结构和算法入门4】

### ISSUE THREAD

**Issue by chengchengxu15** [chengchengxu15/leet_code_lucas#11]
[图灵星球]( https://turingplanet.org/2020/02/22/%e9%93%be%e8%a1%a8-list%e3%80%90%e6%95%b0%e6%8d%ae%e7%bb%93%e6%9e%84%e5%92%8c%e7%ae%97%e6%b3%953%e3%80%91/)

- [ ] [707. Design Linked List](https://leetcode.com/problems/design-linked-list/)
- [x] [21. Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/ )https://github.com/chengchengxu15/leet_code_lucas/issues/12
- [x] [206. Reverse Linked List](https://leetcode.com/problems/reverse-linked-list/) https://github.com/chengchengxu15/leet_code_lucas/issues/13
- [x] [141. Linked List Cycle](https://leetcode.com/problems/linked-list-cycle/ )https://github.com/chengchengxu15/leet_code_lucas/issues/14
- [x] [142. Linked List Cycle II](https://leetcode.com/problems/linked-list-cycle-ii/) https://github.com/chengchengxu15/leet_code_lucas/issues/15
- [x] [369.Plus One Linked List](https://www.lintcode.com/problem/904/description) https://github.com/chengchengxu15/leet_code_lucas/issues/16
- [x] [146. LRU Cache](https://leetcode.com/problems/lru-cache/) https://github.com/chengchengxu15/leet_code_lucas/issues/18
