### ISSUE TITLE
Stack and Queue 堆栈和队列「数据结构和算法5」

### ISSUE THREAD

**Issue by chengchengxu15** [chengchengxu15/leet_code_lucas#19]
[图灵星球](https://turingplanet.org/2020/02/24/%e5%a0%86%e6%a0%88%e5%92%8c%e9%98%9f%e5%88%97%e3%80%90%e6%95%b0%e6%8d%ae%e7%bb%93%e6%9e%84%e5%92%8c%e7%ae%97%e6%b3%953%e3%80%91/)

- [x] [20. Valid Parentheses](https://leetcode.com/problems/valid-parentheses/ )https://github.com/chengchengxu15/leet_code_lucas/issues/20
- [x] [402. Remove K Digits](https://leetcode.com/problems/remove-k-digits/)https://github.com/chengchengxu15/leet_code_lucas/issues/21
- [x] [316. Remove Duplicate Letters](https://leetcode.com/problems/remove-duplicate-letters/) https://github.com/chengchengxu15/leet_code_lucas/issues/22
- [ ] [42. Trapping Rain Water](https://leetcode.com/problems/trapping-rain-water/)
- [x] [621. Task Scheduler](https://leetcode.com/problems/task-scheduler/) https://github.com/chengchengxu15/leet_code_lucas/issues/23
- [x] [622. Design Circular Queue](https://leetcode.com/problems/design-circular-queue/) https://github.com/chengchengxu15/leet_code_lucas/issues/27
- [x] [641. Design Circular Deque](https://leetcode.com/problems/design-circular-deque/) https://github.com/chengchengxu15/leet_code_lucas/issues/28
- [x] [225. Implement Stack using Queues](https://leetcode.com/problems/implement-stack-using-queues/) https://github.com/chengchengxu15/leet_code_lucas/issues/25
- [x] [232. Implement Queue using Stacks](https://leetcode.com/problems/implement-queue-using-stacks/) https://github.com/chengchengxu15/leet_code_lucas/issues/26

**Comment by chengchengxu15** [comment]
栈 Stack 是一种后进先出的数据结构，元素从顶端入栈，然后从顶端出栈。 Last In First Out

队列 Queue 是一种先进先出的数据结构，元素从后端入队，然后从前端出队。

**Comment by chengchengxu15** [comment]
python queue 基本用法：
```

from collections import deque
queue = deque(["Eric", "John", "Michael"])
queue.append("Terry")           # Terry 入队
queue.append("Graham")          # Graham 入队
queue.popleft()                 # 队首元素出队
#输出: 'Eric'
queue.popleft()                 # 队首元素出队
#输出: 'John'
print(queue)                           # 队列中剩下的元素
#输出: deque(['Michael', 'Terry', 'Graham'])

```
