### ISSUE TITLE
树和二分查找树（Tree & Binary Search Tree）「数据结构和算法7」

### ISSUE THREAD

**Issue by chengchengxu15** [chengchengxu15/leet_code_lucas#35]
[图灵星球 树和二分查找树（Tree & Binary Search Tree）「数据结构和算法7」 ](https://turingplanet.org/2020/03/17/%e6%a0%91tree-%e4%ba%8c%e5%88%86%e6%9f%a5%e6%89%be%e6%a0%91binary-search-tree%e3%80%8c%e6%95%b0%e6%8d%ae%e7%bb%93%e6%9e%84%e5%92%8c%e7%ae%97%e6%b3%957%e3%80%8d/)

- [x] [94. Binary Tree Inorder Traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/) https://github.com/chengchengxu15/leet_code/issues/37
- [x] [144. Binary Tree Preorder Traversal](https://leetcode.com/problems/binary-tree-preorder-traversal/) https://github.com/chengchengxu15/leet_code/issues/35#issuecomment-899065534
- [x] [145. Binary Tree Postorder Traversal](https://leetcode.com/problems/binary-tree-postorder-traversal/) https://github.com/chengchengxu15/leet_code/issues/35#issuecomment-899065534
- [x] [102. Binary Tree Level Order Traversal](https://leetcode.com/problems/binary-tree-level-order-traversal/)  https://github.com/chengchengxu15/leet_code/issues/35#issuecomment-899065534 https://github.com/chengchengxu15/leet_code/issues/39
- [x] [958. Check Completeness of a Binary Tree](https://leetcode.com/problems/check-completeness-of-a-binary-tree/) https://github.com/chengchengxu15/leet_code/issues/42
- [x] [110. Balanced Binary Tree](https://leetcode.com/problems/balanced-binary-tree/) https://github.com/chengchengxu15/leet_code/issues/38
- [x] [101. Symmetric Tree](https://leetcode.com/problems/symmetric-tree/) https://github.com/chengchengxu15/leet_code/issues/40
- [x] [701. Insert into a Binary Search Tree](https://leetcode.com/problems/insert-into-a-binary-search-tree/)
 https://github.com/chengchengxu15/leet_code/issues/43
- [x] [104. Maximum Depth of Binary Tree](https://leetcode.com/problems/maximum-depth-of-binary-tree/) https://github.com/chengchengxu15/leet_code/issues/41

**Comment by chengchengxu15** [comment]
Preorder Traversal 前序遍历：打印 - 左 - 右
Inorder Traversal 中序遍历：左 - 打印 - 右
Postorder Traversal 后序遍历：左 - 右 - 打印

**Comment by chengchengxu15** [comment]
94 144 145 102 solution https://leetcode-cn.com/problems/binary-tree-preorder-traversal/solution/tu-jie-er-cha-shu-de-si-chong-bian-li-by-z1m/

https://leetcode-cn.com/problems/binary-tree-preorder-traversal/solution/python3-die-dai-bian-li-chang-gui-jie-fa-1egc/
