### ISSUE TITLE
图Graph「算法和数据结构9」

### ISSUE THREAD

**Issue by chengchengxu15** [chengchengxu15/leet_code_lucas#44]
[图灵星球 图Graph「算法和数据结构9」](https://turingplanet.org/2020/04/02/%e5%9b%begraph%e3%80%8c%e7%ae%97%e6%b3%95%e5%92%8c%e6%95%b0%e6%8d%ae%e7%bb%93%e6%9e%849%e3%80%8d/)

- [x] [463. Island Perimeter](https://leetcode.com/problems/island-perimeter/)  https://github.com/chengchengxu15/leet_code/issues/45
- [x] [200. Number of Islands](https://leetcode.com/problems/number-of-islands/) https://github.com/chengchengxu15/leet_code/issues/46
- [x] [695. Max Area of Island](https://leetcode.com/problems/max-area-of-island/) https://github.com/chengchengxu15/leet_code/issues/47
- [x] [1254. Number of Closed Islands](https://leetcode.com/problems/number-of-closed-islands/) https://github.com/chengchengxu15/leet_code/issues/48
- [x] [994. Rotting Oranges](https://leetcode.com/problems/rotting-oranges/) https://github.com/chengchengxu15/leet_code/issues/50
- [x] [841. Keys and Rooms](https://leetcode.com/problems/keys-and-rooms/) https://github.com/chengchengxu15/leet_code/issues/49

**Comment by chengchengxu15** [comment]
深度优先搜索（Depth-First Search）
图的深度优先和树的前序遍历（Pre-order Traversal）有点类似。在深度优先遍历中，我们假设初始状态所有顶点都没被访问，然后从每一顶点v出发，先访问该顶点，然后依次从它的各个未被访问的邻接点出发，深度优先遍历图，直到图中所有和v相通的顶点都被访问到。若遍历完后，还有其他顶点没被访问到，则另选一个未被访问的顶点作为起始点，重复上述过程，直到所有顶点都被访问完为止。


广度优先搜索（Breadth-First Search)
广度优先搜索算法也叫做“宽度优先搜索”或“横向优先搜索”，其方法是从图中的某一顶点v出发，在访问了v之后依次访问v的各个没有访问到的邻接点，然后分别从这些邻接点出发依次访问他们的邻接点，使得先被访问的顶点的邻接点先与后被访问顶点的邻接点被访问，直到图中所有已被访问的顶点的邻接点都被访问到。如果此时图中尚有顶点未被访问，则需要另选一个未曾被访问到的顶点作为新的起始点，重复上述过程，直至图中所有顶点都被访问到为止。换句话说，广度优先搜索遍历图的过程是以v为起点，由近至远，依次访问和v有路径相通且路径长度为1，2，…的顶点。
