### ISSUE TITLE
数据结构和算法简介, 二分查找「数据结构和算法1」

### ISSUE THREAD

**Issue by chengchengxu15** [chengchengxu15/leet_code_lucas#6]
[图灵星球 二分查找「数据结构和算法1」Binary Search](https://turingplanet.org/2020/01/23/%e6%95%b0%e6%8d%ae%e7%bb%93%e6%9e%84%e5%92%8c%e7%ae%97%e6%b3%95%e7%ae%80%e4%bb%8b%e3%80%90%e6%95%b0%e6%8d%ae%e7%bb%93%e6%9e%84%e5%92%8c%e7%ae%97%e6%b3%951%e3%80%91/)

- [x] [704. Binary Search]( https://leetcode.com/problems/binary-search/submissions/ )https://github.com/chengchengxu15/leet_code_lucas/issues/17
- [x] [744. Find Smallest Letter Greater Than Target](https://leetcode.com/problems/find-smallest-letter-greater-than-target/) https://github.com/chengchengxu15/leet_code_lucas/issues/7
- [x] [74. Search a 2D Matrix](https://leetcode.com/problems/search-a-2d-matrix/)https://github.com/chengchengxu15/leet_code_lucas/issues/8
- [x] [540. Single Element in a Sorted Array](https://leetcode.com/problems/single-element-in-a-sorted-array/) https://github.com/chengchengxu15/leet_code_lucas/issues/9
- [x] [34. Find First and Last Position of Element in Sorted Array](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/) https://github.com/chengchengxu15/leet_code_lucas/issues/10
